// Generated by build script, do not edit!
#ifndef RC_INVOKED

#include "Configuration/IntegerDefinitions.h"
#include "Runtime/Testing/Fakeable.h"

namespace UnityConfig
{
    extern const char* const UnityCompany = "Unity Technologies ApS";
    extern const char* const UnityCopyright = "(c) 2023 Unity Technologies ApS. All rights reserved.";
    extern const bool HardwareStatsEnabled = 1;
    extern const char* const BuildRoot = "C:/build/output/unity/unity";

    extern const char* const UnityVersion = "2022.2.5f1";
    extern const char* const UnityVersionDigits = "2022.2.5";
    extern const char* const UnityVersionSuffix = "f1";
    extern const UInt32 UnityVersionVer = 2022;
    extern const UInt32 UnityVersionMajor = 2;
    extern const UInt32 UnityVersionMinor = 5;
    extern const bool UnityVersionIsBeta = 0;

    extern const char* const UnityVersionUnderHash = "2022.2.5f1_551d45108343";
    extern const char* const UnityVersionUnderHash_Verbose = "2022.2.5f1_551d45108343";
    extern const char* const UnityVersionUnderHash_WithParens = "2022.2.5f1 (551d45108343)";

    // A numeric representation of the version control hash
    extern const UInt64 UnityVersionBuild = 5578053;

    extern const UInt64 UnityVersionDate = 1674629641;
    extern const char* const UnityVersionBranch = "2022.2/staging";
    extern const char* const UnityVersionDisplay = "2022.2.5f1";
    extern const char* const UnityVersionDisplay_Verbose = "2022.2.5f1.112.8802";
    extern const char* const UnityVersionRevision = "551d45108343";

    // Wide strings
    extern const wchar_t* const L_UnityVersionUnderHash_WithParens = L"2022.2.5f1 (551d45108343)";
    extern const wchar_t* const L_UnityVersion = L"2022.2.5f1";
}

#else // Generated by build script for sole use by the Windows resource compiler, do not use for anything else

    #define UNITY_COMPANY "Unity Technologies ApS"
    #define UNITY_COPYRIGHT "(c) 2023 Unity Technologies ApS. All rights reserved."
    #define UNITY_VERSION_VER 2022
    #define UNITY_VERSION_MAJ 2
    #define UNITY_VERSION_MIN 5
    #define UNITY_IS_BETA 0
    #define UNITY_VERSION_UNDER_HASH "2022.2.5f1_551d45108343"
    #define UNITY_VERSION_PARENS_HASH "2022.2.5f1 (551d45108343)"
    #define UNITY_VERSION_BLD 5578053
    #define UNITY_VERSION_WIN "2022.2.5.5578053"

#endif // !RC_INVOKED
